version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - 5432:5432
    hostname: postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5555:80"
    restart: unless-stopped