export const TYPES = {
	App: Symbol.for('App'),
	IConfigService: Symbol.for('IConfigService'),
	ILoggerService: Symbol.for('ILoggerService'),
	IDatabaseService: Symbol.for('IDatabaseService'),
	IDatabase: Symbol.for('IDatabase'),
	IExceptionFilter: Symbol.for('IExceptionFilter'),
	IProductController: Symbol.for('IProductController'),
	IProductRepository: Symbol.for('IProductRepository'),
	IProductService: Symbol.for('IProductService'),
	IUserService: Symbol.for('IUserService'),
	IUserController: Symbol.for('IUserController'),
	IUserRepository: Symbol.for('IUserRepository'),
	ISeed: Symbol.for('Seed'),
	IAuthController: Symbol.for('IAuthController'),
	IAuthService: Symbol.for('IAuthService'),
	ICategoryController: Symbol.for('ICategoryController'),
	ICategoryRepository: Symbol.for('ICategoryRepository'),
	ICategoryService: Symbol.for('ICategoryService'),
	IMailerService: Symbol.for('IMailerService'),
};
